### ISSUE TITLE
Bug: Module uninstall fails

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/menu_attributes#1]
Message:
`ArgumentCountError: Too few arguments to function config_clear(), 1 passed in /mypath/backdrop/modules/menu_attributes/menu_attributes.install on line 28 and exactly 2 expected in config_clear() (line 72 von /mypath/backdrop/core/includes/config.inc). `

**Comment by olafgrabienski** [comment]
Reopening: Today I installed version [1.x-1.0.1](https://github.com/backdrop-contrib/menu_attributes/releases/tag/1.x-1.0.1) of the module, where this issue is mentioned as fixed. Then I tried to uninstall the module and got the same error as in the issue description:

> ArgumentCountError: Too few arguments to function config_clear(), 1 passed in /MY-PATH-TO/modules/menu_attributes/menu_attributes.install on line 28 and exactly 2 expected in config_clear() (line 72 of /homepages/41/d20857419/htdocs/backdrop/core/includes/config.inc).

**Comment by quicksketch** [comment]
Thanks for testing @olafgrabienski, sorry it it looks like I may have made a release that didn't fix the problem.

It looks like somehow I committed the change, but then did not include the fix in the release. Here's the commit, with all instances of `config_clear()` removed. However, looking at the 1.x-1.0.1 tag, the uninstall hook still has `config_clear()` present. It looks like somehow I tagged the wrong commit as the release. Maybe I forgot to pull down?

I'll make a new release today. If you're interested, could you validate the 1.x-1.x branch as working when you uninstall?

**Comment by quicksketch** [comment]
Okay, new 1.0.2 release is out that should really fix this issue. The git code included the fix but I must have made a mistake when doing the tagging of 1.0.1. Thanks @olafgrabienski!

**Comment by olafgrabienski** [comment]
> new 1.0.2 release is out that should really fix this issue

Thanks for making the new release, it works for me! After updating the module to version `1.0.2`, I was able to uninstall it.
