### ISSUE TITLE
Uninstall error: Call to undefined function drupal_load()

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/menu_attributes#2]
**Steps to reproduce**

1. Disable module (using GUI)
2. Uninstall module (using GUI)

**Expected result** Uninstalls and success message

**Actual result**
`Error: Call to undefined function drupal_load() in menu_attributes_uninstall() (line 25 of /app/docroot/modules/menu_attributes/menu_attributes.install).`

![image](https://user-images.githubusercontent.com/20357797/154805722-7ac52ee8-06d1-418d-b8e1-79a7d2666ab1.png)

**Comment by quicksketch** [comment]
Fixed by https://github.com/backdrop-contrib/menu_attributes/pull/7. Thanks @yorkshire-pudding!
