### ISSUE TITLE
Offer to (co-)maintain the menu_attributes module.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/menu_attributes#4]
Hey @quicksketch 👋🏼 

I will start using this module in a site I've built for my cousin, so I'd like to bring it up to date with commits from the 7.x version. I would like to offer to (co-)maintain the module in general if you agree.

Let me know.

PR that adds me as a maintainer: https://github.com/backdrop-contrib/menu_attributes/pull/5

**Comment by quicksketch** [comment]
Welcome and Thank You!

**Comment by klonos** [comment]
Thank YOU @quicksketch 🙏🏼
