### ISSUE TITLE
PHP Deprecated:  Required parameter $complete_form

### ISSUE THREAD

**Issue by shabibalm** [backdrop-contrib/menu_attributes#6]
problem =
Deprecated: Required parameter $complete_form follows optional parameter $item in menu_attributes.module 196

solution =
https://www.drupal.org/project/menu_attributes/issues/3256013#comment-14352460

https://git.drupalcode.org/issue/menu_attributes-3279533/-/commit/910f8cecd785c5b8981d08c25f0dcf54676f5ed4

**Comment by quicksketch** [comment]
Thanks @shabibalm for finding this problem and cross-referencing the Drupal 7 fix! I've merged https://github.com/backdrop-contrib/menu_attributes/pull/8 which applies the same fix to this Backdrop version.
